image:
  name: python:3.10
  pull_policy: [always, if-not-present]

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTEST_COVERAGE_THRESHOLD: "25"
  FLAKE8_MAX_LINE_LENGTH: 88

stages:
  - test
  - security
  - style
  - docs
  - build

cache:
  policy: pull-push
  paths:
    - .venv/
    - .cache/pip

before_script:
  - pip install poetry
  - poetry config http-basic.mupol-plaintext $CI_DEPLOY_USER $CI_DEPLOY_PASSWORD
  - poetry config virtualenvs.in-project true
  - poetry install --all-extras
  - source .venv/bin/activate

Pytest:
  stage: test
  script:
    - pytest --version
    - pytest --cov --cov-fail-under=${PYTEST_COVERAGE_THRESHOLD} --cov-report xml --color=yes .
  artifacts:
    paths:
      - .coverage

MyPy:
  stage: style
  script:
    - mypy --version
    - mypy --install-types --non-interactive --ignore-missing-imports --allow-subclassing-any --explicit-package-bases --strict .

Black:
  stage: style
  script:
    - black --version
    - black --check --diff --color .

isort:
  stage: style
  script:
    - isort --version
    - isort --check --profile=black --diff --color .

Flake8:
  stage: style
  script:
    - flake8 --version
    - flake8 --statistics --max-line-length=${FLAKE8_MAX_LINE_LENGTH} --extend-exclude "./.venv/*"

Bandit:
  stage: security
  script:
    - bandit --version
    - bandit --verbose --recursive . -x "./tests/*,./.venv/*"

PDoc:
  stage: docs
  script:
    - pdoc --version
    - pdoc mupol.mpc -o docs
  artifacts:
    paths:
      - docs/

Poetry build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - poetry config repositories.mupol-mpc https://git-service.ait.ac.at/api/v4/projects/sct-crypto%2Fmupol%2Fmupol-mpc-demonstrator/packages/pypi
    - poetry publish --build --repository mupol-mpc -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD
